update

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -36,28 +36,47 @@ jobs:
           fetch-depth: 0
 
 
-  # validate:
-  #   name: Validate
-  #   needs: checkout
-  #   runs-on: ubuntu-latest
-  #   timeout-minutes: 5
-  #   steps:
-  #     - name: Check for Conventional Branches
-  #       uses: ./.github/actions/conventional-branches
+  validate:
+    name: Validate
+    needs: checkout
+    runs-on: ubuntu-latest
+    timeout-minutes: 1
+    steps:
+      - name: Branches
+        shell: bash
+        run: |
+          BRANCH_NAME="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
+
+          echo "🔍 Validating branch: $BRANCH_NAME"
+          
+          if [[ "$BRANCH_NAME" =~ ^(main|staging|topic\/[a-z0-9-]+|rollback\/[a-z0-9-]+|debug\/[a-z0-9-]+)$ ]]; then
+            echo "✅ Follows accepted conventions."
+            exit 0
+          else
+            echo "❌ Invalid branch name: '$BRANCH_NAME'                  "
+            echo "Allowed conventions:                                    "
+            echo "  - main                                                "
+            echo "  - staging                                             "
+            echo "  - rollback/<lowercase-name> (letters, numbers, dashes)"
+            echo "  - topic/<lowercase-name> (letters, numbers, dashes)   "
+            echo "  - debug/<lowercase-name> (letters, numbers, dashes)   "
+            exit 1
+          fi
 
 
   assemble:
     name: Assemble Debug
-    needs: checkout
+    if: ${{ always() }}
+    needs: validate
     runs-on: ubuntu-latest
-    timeout-minutes: 20
+    timeout-minutes: 10
     steps:
       - name: Checkout
         uses: actions/checkout@v5
         with:
           fetch-depth: 0
 
-      - name: Configure Environment
+      - name: Configure the Android Environment
         uses: ./.github/actions/setup-android
         with:
           java-distros: 'temurin'
